# Generated by Django 3.2.20 on 2023-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('static_points', models.IntegerField()),
                ('sp_flag', models.IntegerField()),
                ('os', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('star', models.FloatField()),
                ('release', models.CharField(max_length=30)),
                ('easy_month', models.IntegerField()),
                ('poweroff', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('difficultyText', models.CharField(max_length=30)),
                ('user_owns_count', models.IntegerField()),
                ('authUserInUserOwns', models.BooleanField()),
                ('root_owns_count', models.IntegerField()),
                ('counterCake', models.IntegerField()),
                ('counterVeryEasy', models.IntegerField()),
                ('counterEasy', models.IntegerField()),
                ('counterTooEasy', models.IntegerField()),
                ('counterMedium', models.IntegerField()),
                ('counterBitHard', models.IntegerField()),
                ('counterHard', models.IntegerField()),
                ('counterTooHard', models.IntegerField()),
                ('counterExHard', models.IntegerField()),
                ('counterBrainFuck', models.IntegerField()),
                ('predicted_minutes', models.IntegerField()),
            ],
        ),
    ]
