# Generated by Django 3.2.20 on 2023-12-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='authUserInRootOwns',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
