# Generated by Django 3.2.20 on 2023-12-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htb', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.CharField(default=' ', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='staff_pick',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
