# Generated by Django 3.2.20 on 2023-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htb', '0005_auto_20231226_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='num_minutes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
